In [33]:
import pandas as pd

cancer_df = pd.read_csv("C:/Users/noapo/Downloads/pnas_tpm_96_nodup.txt", sep="\t", header=None)
cancer_df.set_index(cancer_df.columns[0], inplace=True)
cancer_df.columns = [f'C{i+1}' for i in range(cancer_df.shape[1])]
cancer_df.head()

,C1,C2,C3,C4,C5,C6,C7,C8,C9,C10,...,C87,C88,C89,C90,C91,C92,C93,C94,C95,C96
0,,,,,,,,,,,,,,,,,,,,,
ENSG00000000003,7.071605,60.610797,58.255903,29.917356,24.500322,25.311091,37.394452,15.354658,24.839014,24.591295,...,14.134044,10.803910,6.068982,12.714350,15.983392,0.000000,38.189128,15.608352,51.519267,30.805593
ENSG00000000005,13.279391,47.424080,60.455497,6.482332,53.675826,31.686900,32.409716,0.000000,48.976056,46.178684,...,0.000000,12.172853,136.759411,28.650721,0.000000,0.000000,5.976111,6.280734,241.863225,0.000000
ENSG00000000419,0.000000,0.000000,23.040206,8.646690,20.456404,42.266702,21.615428,11.538256,18.665274,76.996356,...,79.657691,8.118597,0.000000,0.000000,0.000000,179.178412,15.942897,0.000000,0.000000,0.000000
ENSG00000000457,6.212355,2.218590,12.120963,6.065120,16.142519,37.059356,7.580945,0.000000,0.000000,21.603278,...,18.624986,15.660412,33.988677,0.000000,36.858404,83.788404,18.172309,2.938248,14.547636,10.148436
ENSG00000000460,34.038592,35.828348,55.926653,10.494273,14.482668,19.236768,13.117055,4.667898,18.877984,12.459809,...,17.903438,19.706680,23.062537,1.932615,28.344382,3.020339,27.411791,1.694651,3.729079,7.804221

In [34]:
oncogenes_df = pd.read_csv("C:/Users/noapo/Downloads/cancerGeneList.tsv", sep="\t")
oncogenes_df.head()

,Hugo Symbol,Entrez Gene ID,GRCh37 Isoform,GRCh37 RefSeq,GRCh38 Isoform,GRCh38 RefSeq,Is Oncogene,Is Tumor Suppressor Gene,# of occurrence within resources (Column J-P),OncoKB Annotated,MSK-IMPACT,MSK-HEME,FOUNDATION ONE,FOUNDATION ONE HEME,Vogelstein,COSMIC CGC (v99),Gene Aliases
0,ABL1,25,ENST00000318560,NM_005157.4,ENST00000318560,NM_005157.4,Yes,No,7,Yes,Yes,Yes,Yes,Yes,Yes,Yes,"ABL, JTK7, c-ABL"
1,AKT1,207,ENST00000349310,NM_001014431.1,ENST00000349310,NM_001014431.1,Yes,No,7,Yes,Yes,Yes,Yes,Yes,Yes,Yes,"AKT, PKB, PRKBA, RAC, RAC-alpha"
2,ALK,238,ENST00000389048,NM_004304.4,ENST00000389048,NM_004304.4,Yes,No,7,Yes,Yes,Yes,Yes,Yes,Yes,Yes,CD246
3,AMER1,139285,ENST00000330258,NM_152424.3,ENST00000374869,NM_152424.3,No,Yes,7,Yes,Yes,Yes,Yes,Yes,Yes,Yes,"FAM123B, FLJ39827, RP11-403E24.2, WTX"
4,APC,324,ENST00000257430,NM_000038.5,ENST00000257430,NM_000038.5,No,Yes,7,Yes,Yes,Yes,Yes,Yes,Yes,Yes,"DP2.5, PPP1R46"

In [35]:
from pybiomart import Dataset

dataset = Dataset(name='hsapiens_gene_ensembl', host='http://www.ensembl.org')
mapping_df = dataset.query(attributes=['ensembl_gene_id', 'hgnc_symbol'])
mapping_df.columns = ['Gene stable ID', 'HGNC symbol']
mapping_df = mapping_df[mapping_df['HGNC symbol'] != '']

ensg_to_symbol = dict(zip(mapping_df['Gene stable ID'], mapping_df['HGNC symbol']))

cancer_df['gene_symbol'] = cancer_df.index.map(ensg_to_symbol)
cancer_df = cancer_df[cancer_df['gene_symbol'].notnull()]
cancer_df.set_index('gene_symbol', inplace=True)
cancer_df.head()

,C1,C2,C3,C4,C5,C6,C7,C8,C9,C10,...,C87,C88,C89,C90,C91,C92,C93,C94,C95,C96
gene_symbol,,,,,,,,,,,,,,,,,,,,,
TSPAN6,7.071605,60.610797,58.255903,29.917356,24.500322,25.311091,37.394452,15.354658,24.839014,24.591295,...,14.134044,10.803910,6.068982,12.714350,15.983392,0.000000,38.189128,15.608352,51.519267,30.805593
TNMD,13.279391,47.424080,60.455497,6.482332,53.675826,31.686900,32.409716,0.000000,48.976056,46.178684,...,0.000000,12.172853,136.759411,28.650721,0.000000,0.000000,5.976111,6.280734,241.863225,0.000000
DPM1,0.000000,0.000000,23.040206,8.646690,20.456404,42.266702,21.615428,11.538256,18.665274,76.996356,...,79.657691,8.118597,0.000000,0.000000,0.000000,179.178412,15.942897,0.000000,0.000000,0.000000
SCYL3,6.212355,2.218590,12.120963,6.065120,16.142519,37.059356,7.580945,0.000000,0.000000,21.603278,...,18.624986,15.660412,33.988677,0.000000,36.858404,83.788404,18.172309,2.938248,14.547636,10.148436
FIRRM,34.038592,35.828348,55.926653,10.494273,14.482668,19.236768,13.117055,4.667898,18.877984,12.459809,...,17.903438,19.706680,23.062537,1.932615,28.344382,3.020339,27.411791,1.694651,3.729079,7.804221

In [36]:
oncogene_genes = oncogenes_df['Hugo Symbol'].tolist()
filtered_df = cancer_df.loc[cancer_df.index.intersection(oncogene_genes)]
filtered_df.head()

,C1,C2,C3,C4,C5,C6,C7,C8,C9,C10,...,C87,C88,C89,C90,C91,C92,C93,C94,C95,C96
gene_symbol,,,,,,,,,,,,,,,,,,,,,
RAD52,17.859037,7.289047,26.548476,24.908245,11.785623,15.219543,9.340032,0.000000,16.130539,8.872038,...,33.145289,2.338699,3.284347,0.000000,2.883241,17.205119,2.296310,26.546970,7.965901,11.114031
LASP1,7.569685,2.162662,0.000000,2.956112,3.496796,14.450052,5.542378,0.000000,23.929669,2.632335,...,12.103647,2.775569,0.000000,4.899553,22.241913,45.942857,14.988943,4.296268,0.000000,3.297535
RECQL,2.829515,36.377709,7.360913,33.149458,22.874028,3.375854,6.905723,3.686256,29.816021,9.839556,...,5.655363,5.187478,0.000000,45.785793,3.197666,0.000000,5.093456,26.765437,0.000000,9.244532
UPF1,21.131216,7.102583,11.317831,15.776187,7.177581,22.245309,10.617951,1.619381,11.788423,6.483809,...,17.390900,22.788714,0.000000,2.681841,4.214226,0.000000,5.593918,2.351624,5.174748,5.414859
HOXA11,9.267368,0.000000,0.000000,45.238641,10.702592,5.528382,5.654491,0.000000,0.000000,24.170248,...,9.261362,8.495142,0.000000,0.000000,0.000000,0.000000,8.341169,0.000000,19.290348,0.000000

In [37]:
metadata_df = pd.read_csv("C:/Users/noapo/Downloads/pnas_patient_info.csv")

column_names = [f"C{i+1}" for i in range(len(metadata_df))]
recur_statuses = metadata_df['recurStatus'].tolist()
new_column_names = [f"{name}_{status}" for name, status in zip(column_names, recur_statuses)]

filtered_df.columns = new_column_names
filtered_df.head()

,C1_R,C2_R,C3_R,C4_R,C5_R,C6_R,C7_R,C8_R,C9_R,C10_R,...,C87_N,C88_N,C89_N,C90_N,C91_N,C92_N,C93_N,C94_N,C95_N,C96_N
gene_symbol,,,,,,,,,,,,,,,,,,,,,
RAD52,17.859037,7.289047,26.548476,24.908245,11.785623,15.219543,9.340032,0.000000,16.130539,8.872038,...,33.145289,2.338699,3.284347,0.000000,2.883241,17.205119,2.296310,26.546970,7.965901,11.114031
LASP1,7.569685,2.162662,0.000000,2.956112,3.496796,14.450052,5.542378,0.000000,23.929669,2.632335,...,12.103647,2.775569,0.000000,4.899553,22.241913,45.942857,14.988943,4.296268,0.000000,3.297535
RECQL,2.829515,36.377709,7.360913,33.149458,22.874028,3.375854,6.905723,3.686256,29.816021,9.839556,...,5.655363,5.187478,0.000000,45.785793,3.197666,0.000000,5.093456,26.765437,0.000000,9.244532
UPF1,21.131216,7.102583,11.317831,15.776187,7.177581,22.245309,10.617951,1.619381,11.788423,6.483809,...,17.390900,22.788714,0.000000,2.681841,4.214226,0.000000,5.593918,2.351624,5.174748,5.414859
HOXA11,9.267368,0.000000,0.000000,45.238641,10.702592,5.528382,5.654491,0.000000,0.000000,24.170248,...,9.261362,8.495142,0.000000,0.000000,0.000000,0.000000,8.341169,0.000000,19.290348,0.000000

In [38]:
import numpy as np
from sklearn.decomposition import PCA

# PCA to get the top 100 genes
X = cancer_df.T 

# PCA
pca = PCA()
pca.fit(X)

loadings = pca.components_.T  

# importance vals
k = 2
importance_scores = np.sum(loadings[:, :k]**2, axis=1)

# Get top 100 genes
n_genes = min(100, cancer_df.shape[0])
top_100_genes = cancer_df.index[np.argsort(importance_scores)[::-1][:n_genes]]

print("Top 100 genes:", top_100_genes.tolist())

Top 100 genes: ['HBB', 'MT-TP', 'MT-CYB', 'MT-RNR2', 'MT-ND3', 'MT-ND5', 'MT-ND4', 'MT-ND4L', 'MT-RNR1', 'MT-ND2', 'MT-ND1', 'MT-CO3', 'MT-ND6', 'MT-CO2', 'MT-ATP6', 'MT-ATP8', 'MT-CO1', 'MT-TL1', 'MT-TT', 'MT-TG', 'MT-TH', 'RN7SL2', 'RNA5SP202', 'MT-TS2', 'MIR1911', 'RNA5SP145', 'MT-TL2', 'MT-TF', 'RNA5SP243', 'MT-TI', 'RNU6-411P', 'RNU7-196P', 'MT-TR', 'MT-TW', 'MT-TD', 'MT-TM', 'RNU6-284P', 'RNU6-172P', 'MT-TY', 'PPBP', 'MIR515-1', 'RNU4-2', 'RNU6-1246P', 'RAC2', 'MIR4527', 'MIR548A3', 'MTATP6P1', 'RNU6-627P', 'IGHD1-14', 'MTND1P23', 'SUB1P2', 'KRTAP5-13P', 'KRAS', 'RNU6-826P', 'RNU6-890P', 'MT-TV', 'TIMM8AP1', 'IGHD5-24', 'IFITM3P7', 'RNU1-140P', 'RN7SL130P', 'RPS29P31', 'RNU6-755P', 'FTLP19', 'H2AC17', 'H2AC8', 'RPS26P20', 'RNY3P13', 'RNU6-1108P', 'FTL', 'RPS15AP10', 'SLC4A8-AS1', 'RNU6-39P', 'RN7SL646P', 'HBA1', 'IFNA14', 'RNA5SP220', 'MIR5685', 'S100A9', 'RN7SKP271', 'RNU7-165P', 'RNA5SP467', 'RPL27AP9', 'COX6CP18', 'MTND2P28', 'TPM3P3', 'RNA5SP355', 'MIR8063', 'RNY3', 'RN7SKP55', 'RNA5SP387', 'MT-TE', 'IGHV1-24', 'LYPLA1P2', 'RN7SL477P', 'RNU6-588P', 'PF4', 'RNU1-114P', 'RNA5SP255', 'RPL31P34']

In [39]:
# keep genes in both the top 100 and cancer gene list (union)
keep_genes = set(top_100_genes).union(set(filtered_df.index))
print("Genes to keep:", keep_genes)
print(len(keep_genes), "genes to keep")

# Filter the combined data to keep only the genes in keep_genes
filtered_df = filtered_df.loc[filtered_df.index.isin(keep_genes)]

Genes to keep: {'MTCP1', 'HOXC11', 'DKK2', 'LRP6', 'SMAD3', 'TFE3', 'SIX1', 'AKT1S1', 'STK40', 'PRSS1', 'H3-4', 'SETD1B', 'PTPN13', 'MS4A1', 'NCOA3', 'NADK', 'MLH3', 'CUL3', 'ABI1', 'ALDH2', 'RNU6-172P', 'PTPN2', 'BCL2L2', 'SOX17', 'LRP5', 'HMGA2', 'ASXL1', 'SUFU', 'HLA-C', 'HOXD11', 'MT-TE', 'MT-CO2', 'SAMD9', 'CUX1', 'ATP6AP1', 'INTS6', 'TRIM27', 'FCGR2B', 'CACNA1D', 'CTDNEP1', 'BBC3', 'ERCC2', 'EPHB1', 'KIT', 'NF1', 'ATP2B3', 'FLT3', 'SESN3', 'BRIP1', 'STAT3', 'SLC4A8-AS1', 'ZFHX3', 'PSIP1', 'TLL2', 'ARID3C', 'IL21R', 'EIF3E', 'EP300', 'FUS', 'H3-3B', 'TRAF5', 'ZNF292', 'MDS2', 'CALR', 'FCRL4', 'H3C15', 'FGF9', 'SND1', 'MT-ND5', 'PRF1', 'USP6', 'FHIT', 'MLH1', 'PPM1D', 'DKK3', 'RAF1', 'MYO5A', 'AURKA', 'FGF7', 'PPP1CB', 'POLH', 'GAB2', 'SMARCA4', 'TSC2', 'IRS4', 'CMTR2', 'RN7SKP271', 'ABCB1', 'KDM5C', 'AKT2', 'FLCN', 'FIP1L1', 'NIN', 'NBN', 'PARP3', 'RPN1', 'TIGAR', 'MEF2B', 'SNCAIP', 'FANCB', 'MED12', 'SLC1A2', 'MT-ATP8', 'PRPF8', 'PNRC1', 'HOOK3', 'MAD2L2', 'MTND1P23', 'RNA5SP243', 'EGR2', 'GREM1', 'E2F3', 'LTB', 'SFRP2', 'KDSR', 'CDK12', 'FOXA1', 'POT1', 'PHF6', 'SS18L1', 'PTCH1', 'MDC1', 'EPAS1', 'RIT1', 'IFNA14', 'FANCA', 'REST', 'ZFP36L2', 'MAP3K21', 'TPM3P3', 'ROS1', 'FGF23', 'LRIG3', 'MSH6', 'H2AC11', 'PARP2', 'CCDC6', 'KMT2A', 'TRIM33', 'MAPK3', 'RAD52', 'ELP2', 'PUM1', 'IL3', 'NOTCH1', 'CLIP1', 'GADD45B', 'ALOX12B', 'PIK3R2', 'TPM3', 'FGF14', 'RPS29P31', 'HFE', 'TET2', 'IKZF3', 'AFF1', 'IGHD5-24', 'KRTAP5-13P', 'PDS5B', 'ACTG1', 'TERC', 'ZMYM2', 'PTPRB', 'KIF5B', 'NUTM2A', 'ETAA1', 'SLIT2', 'MAP3K14', 'ARHGAP35', 'RN7SL130P', 'SOX9', 'SEC31A', 'REV3L', 'RAC2', 'SDHB', 'FZR1', 'BIRC3', 'FOXO4', 'AKT1', 'DNMT3A', 'CHEK1', 'ERRFI1', 'TCL1A', 'H2AC16', 'CCT6B', 'HNF1B', 'ATXN7', 'TNFSF13', 'CYP19A1', 'ARHGEF12', 'CDC73', 'CCNE1', 'LMNA', 'PAX8', 'CDH11', 'YY1AP1', 'DKK1', 'PRKN', 'RPS15AP10', 'ACTB', 'BRAF', 'ROBO1', 'MTHFD2', 'EMSY', 'STIL', 'KLHL6', 'NUTM1', 'TCL1B', 'RMI2', 'PRDM1', 'BRCA1', 'LZTR1', 'IKBKB', 'SMYD3', 'PTPN1', 'ZNF24', 'AGO2', 'GABRA6', 'REL', 'U2AF1', 'BCL6', 'PIM1', 'ATXN2', 'CYLD', 'NSD1', 'P2RY8', 'NFE2', 'RNF43', 'TFPT', 'POU3F4', 'RAD17', 'IDH1', 'DAXX', 'DDX6', 'IKBKE', 'HDAC7', 'MAP3K7', 'CD79A', 'SLIT3', 'ERBB2', 'KDM5A', 'DUSP22', 'LYL1', 'INHA', 'H2AC6', 'SOCS3', 'RN7SL477P', 'PTPN11', 'SETBP1', 'CDKN1A', 'CDH4', 'RNU6-1246P', 'CSDE1', 'ARHGAP26', 'VAV2', 'SMARCB1', 'SDHA', 'CASP8', 'FGF6', 'SERPINB3', 'KEAP1', 'DUSP2', 'CNBP', 'VTCN1', 'STAT5B', 'PMAIP1', 'DCUN1D1', 'DDR2', 'TPMT', 'MAP3K13', 'RAD50', 'NCOA2', 'MAL2', 'TOP2A', 'IGF1R', 'DHX15', 'BRD3', 'CCNB1IP1', 'MITF', 'CDKN1C', 'GPHN', 'RASA1', 'ARID4B', 'CNOT3', 'GSTP1', 'KMT2D', 'AGK', 'CREBBP', 'MSN', 'MLLT11', 'LMO1', 'PALB2', 'HSP90AB1', 'SMARCE1', 'MT-ND2', 'RHEB', 'XPA', 'RNU6-826P', 'BACH2', 'CREB1', 'ECSIT', 'RARA', 'PTK6', 'PARP1', 'MT-TD', 'COL1A1', 'FOXF1', 'RPTOR', 'WRN', 'OMD', 'EPOR', 'CDK8', 'HBB', 'ECT2L', 'GNA13', 'PBX1', 'RECQL', 'TMSB4XP8', 'MT-ND1', 'IRF1', 'FTLP19', 'SRC', 'PHOX2B', 'KRAS', 'TFEB', 'TPR', 'ALOX5', 'GNAQ', 'TAP2', 'HDAC1', 'PIK3C2G', 'RNA5SP202', 'UCHL1', 'PTPRO', 'LMO2', 'BRD4', 'CDKN2A', 'ETS1', 'RNA5SP145', 'TCF12', 'CHIC2', 'SEPTIN6', 'IQGAP1', 'RNA5SP467', 'GLI1', 'PPBP', 'MT-TG', 'SSX4', 'H3C11', 'SPEN', 'EPCAM', 'RNU6-1108P', 'MIB1', 'CYP17A1', 'NKX2-1', 'TAF1', 'CBLC', 'PF4', 'SLC45A3', 'MST1', 'FBXO11', 'WAS', 'RPL22', 'ABRAXAS1', 'RNU4-2', 'PIK3C3', 'BCL7A', 'MT-ATP6', 'SETD4', 'CARS1', 'CDKN2B', 'HIRA', 'RB1', 'MCL1', 'ATP6V1B2', 'DDX10', 'ACVR2A', 'SMAD2', 'HTATIP2', 'MYOD1', 'SRSF3', 'MYBL1', 'PIGA', 'RNU1-140P', 'RPS6KA4', 'SETD1A', 'ANKRD11', 'TAF15', 'MAGI2', 'PPFIBP1', 'RNU6-284P', 'HNF1A', 'PTPN6', 'CTNNA1', 'ARID2', 'CCND3', 'LRRK2', 'MYB', 'DPYD', 'MTHFR', 'MT-TS2', 'MAML2', 'RTEL1', 'SUB1P2', 'H3C8', 'PRKACA', 'MT-ND6', 'PMS2', 'COP1', 'PICALM', 'VHL', 'POLD1', 'S1PR2', 'MIR515-1', 'IRS2', 'PAK3', 'MPL', 'HOXA9', 'ASXL2', 'TP63', 'ATR', 'SOCS1', 'MECOM', 'IGF1', 'RPS26P20', 'ETV1', 'ACSL6', 'CRKL', 'ATP1A1', 'IKZF2', 'ZRSR2', 'MRTFA', 'RNU6-755P', 'FH', 'STAG2', 'EPHB4', 'RNA5SP355', 'ZNF331', 'TFG', 'ERBB3', 'SHQ1', 'TMEM30A', 'GPC3', 'YY1', 'PPP2R1A', 'TSC1', 'MGA', 'MT-TP', 'SBDS', 'KDR', 'TFRC', 'EIF4E', 'MLLT1', 'BARD1', 'FURIN', 'ETV4', 'CD79B', 'POU3F2', 'TOP1', 'CTLA4', 'SFRP1', 'SOCS2', 'STAT5A', 'CTCF', 'MSI2', 'CHD4', 'AIP', 'EPHA7', 'SF3B1', 'GTSE1', 'RRAS2', 'DKK4', 'NDRG1', 'NOD1', 'TEK', 'TLX1', 'DDB2', 'PDCD11', 'ARNT', 'HSD3B1', 'MIR548A3', 'FGF19', 'SET', 'BTLA', 'ARID1B', 'MLLT10', 'SETD7', 'GOLGA5', 'CHD2', 'PTP4A1', 'MGAM', 'RABEP1', 'RPL10', 'PTPRD', 'INHBA', 'USP8', 'MT-TF', 'BUB1B', 'DTX1', 'NOTCH2', 'GATA1', 'NUP214', 'MT-TR', 'SQSTM1', 'MRE11', 'PDGFRA', 'COL2A1', 'EZHIP', 'SP140', 'ATF1', 'HMGA1', 'MALT1', 'MLF1', 'EIF4A2', 'CHCHD7', 'HOXA13', 'SOX2', 'MAPK1', 'CLTCL1', 'EXT1', 'APEX1', 'PAX3', 'HERPUD1', 'BCL2L1', 'PRKAR1A', 'FGF10', 'EPS15', 'EIF2B1', 'TET3', 'FGFR2', 'NCSTN', 'SMO', 'PCSK7', 'BRCA2', 'H1-2', 'ERBB4', 'JAK1', 'FANCG', 'LPP', 'ID1', 'CCNQ', 'PDGFB', 'AXL', 'FNBP1', 'EIF1AX', 'MYD88', 'RIOK2', 'CNTRL', 'RN7SKP55', 'IRS1', 'TRAF2', 'SAMD9L', 'H2BC8', 'PC', 'TGFBR1', 'INPP4A', 'IFNGR1', 'MYCL', 'TMPRSS2', 'FBXW7', 'RNY3P13', 'FSTL3', 'ARFRP1', 'U2AF2', 'CBFB', 'PDCD1', 'YWHAE', 'CCN6', 'NBEAP1', 'ATIC', 'PPARG', 'CREM', 'CDK4', 'TNFAIP3', 'GSK3B', 'PDPK1', 'INSR', 'KMT2B', 'XRCC2', 'PRKD1', 'MIR1911', 'NSD2', 'CRLF2', 'MT-CO1', 'FGF5', 'WDR90', 'HOXC13', 'RRAGC', 'NRAS', 'TLE3', 'CD28', 'NFKB2', 'H3C12', 'SPRED1', 'KBTBD4', 'FANCC', 'BTK', 'RAP1GDS1', 'DDX5', 'MT-RNR2', 'FBXO31', 'STAT1', 'FUBP1', 'UBE2A', 'MT-ND3', 'KTN1', 'CSF3R', 'PPP6C', 'RNA5SP220', 'RICTOR', 'FLT1', 'GATA2', 'MT-TI', 'ELL', 'NUMA1', 'PBRM1', 'GNA12', 'ALB', 'NCOA4', 'NHERF1', 'MEF2C', 'B2M', 'FGF12', 'ATG5', 'KNL1', 'HLA-A', 'CD36', 'RPL31P34', 'ERCC5', 'BCL10', 'MKI67', 'PSMB2', 'MOB3B', 'CTR9', 'HEY1', 'MET', 'TRRAP', 'RYBP', 'HOXD13', 'TNFRSF14', 'KLF3', 'ERF', 'CENPA', 'H2BC11', 'CKS1B', 'FANCE', 'NOTCH4', 'HSP90AA1', 'FOLR1', 'RPS6KB1', 'ATRIP', 'FTL', 'AXIN2', 'NACA', 'PRKDC', 'MAP3K6', 'BTG2', 'XIAP', 'RAB35', 'RNASEH2A', 'MDM4', 'PRDM14', 'BAALC', 'AURKB', 'NFKBIA', 'PHF19', 'CASR', 'SETDB1', 'H3C10', 'STAT4', 'POLG', 'NCOR1', 'DDX41', 'ERC1', 'CTC1', 'TTL', 'CHEK2', 'BAX', 'H2AC8', 'DDX4', 'FGF3', 'NFIB', 'PTPN14', 'ETV5', 'PTPRS', 'ZBTB7A', 'CCND2', 'IDH2', 'FANCL', 'MSI1', 'PIK3R1', 'TIMM8AP1', 'APLNR', 'TET1', 'CEP43', 'RUNX2', 'RAD21', 'ZNF217', 'HGF', 'PTK7', 'MT-RNR1', 'CIITA', 'BCL2', 'PIK3CG', 'MT-CYB', 'TNFRSF17', 'PIK3CD', 'BCL2L11', 'ESCO2', 'SSX1', 'CRBN', 'PDCD1LG2', 'ID3', 'FOXN4', 'FLI1', 'HSD17B2', 'SF3B2', 'NCOR2', 'ING1', 'H2AC17', 'ADGRG4', 'DEK', 'TEC', 'CBFA2T3', 'GAB1', 'CCND1', 'ATRX', 'EML4', 'CRTC1', 'MT-TW', 'FGF1', 'RNA5SP387', 'TIPARP', 'SH2B3', 'CAMTA1', 'SALL4', 'WIF1', 'SUZ12', 'MAP3K1', 'ALK', 'PIK3R3', 'PLAG1', 'ABL1', 'LEF1', 'NTRK2', 'DUSP4', 'H3C6', 'HOXA3', 'EZH2', 'PRKCB', 'SETD2', 'NFKBIE', 'RSPO3', 'RUNX1', 'STK11', 'FGFR1', 'NPM1', 'TBL1XR1', 'PER1', 'TP53BP1', 'GNA11', 'BCL11B', 'APC', 'EBF1', 'HNRNPA2B1', 'GRB7', 'BCOR', 'MBD6', 'AXIN1', 'KEL', 'MSH3', 'NCOA1', 'EGR1', 'GAS7', 'PHLPP2', 'KNSTRN', 'UBTF', 'RNU7-196P', 'AR', 'ARID5A', 'SMC3', 'GATA3', 'SERP2', 'RNU6-588P', 'GPS2', 'MIDEAS', 'IKZF1', 'TLE4', 'TMEM127', 'RNF213', 'CSF1', 'CPS1', 'TRIB3', 'NR4A3', 'EXT2', 'KIAA1549', 'CD22', 'MYH11', 'JAK2', 'KLF4', 'RNU6-411P', 'NTHL1', 'TAP1', 'RPL27AP9', 'FANCD2', 'ADGRA2', 'WWP1', 'KAT6A', 'MAP2K2', 'CDKN2C', 'YAP1', 'EXOSC6', 'KDM4C', 'TCEA1', 'MT-TT', 'PIK3C2B', 'RAD51C', 'DDX3X', 'MLLT3', 'SFPQ', 'TYRO3', 'RAC1', 'EPHA3', 'FGFR4', 'AGGF1', 'ARID1A', 'IL10', 'SESN2', 'CHTF8', 'TENT5C', 'H3C1', 'HOXA11', 'HBA1', 'ERCC6', 'CILK1', 'RNA5SP255', 'HDAC2', 'H3C13', 'TLE1', 'ZNF703', 'NTRK3', 'MST1R', 'ARAF', 'DNMT1', 'AFDN', 'GMPS', 'CANT1', 'H2BC5', 'PATZ1', 'MT-TL2', 'RXRA', 'RALGDS', 'SMC1A', 'CSF1R', 'PLK2', 'MT-TM', 'PHF1', 'FOXO3', 'ANKRD26', 'ESR1', 'DNAJB1', 'EGFL7', 'KCNJ5', 'GNB1', 'CDH1', 'IGHV1-24', 'USP1', 'ALDH1L2', 'NUP98', 'H1-3', 'TAL1', 'RNASEH2B', 'KDM2B', 'EED', 'RBM10', 'H1-4', 'CREB3L2', 'H3-5', 'CD70', 'MTATP6P1', 'CREB3L1', 'ABL2', 'PTPRT', 'MAX', 'NKX3-1', 'STAT2', 'MT-TH', 'NTRK1', 'ITK', 'ACVR1', 'TRIM24', 'SYK', 'POU2F2', 'CD276', 'ACSL3', 'ICOSLG', 'FRS2', 'PRRX1', 'ADHFE1', 'H3C7', 'SETDB2', 'RANBP2', 'NUP93', 'CARM1', 'DNMT3B', 'RNF217-AS1', 'NONO', 'ELOC', 'TRIP13', 'OLIG2', 'MT-TY', 'TERT', 'ELK4', 'EZH1', 'BCL3', 'CYSLTR2', 'FYN', 'EZR', 'CD58', 'FGF4', 'JARID2', 'TUSC3', 'PAX7', 'LRP1B', 'STRN', 'RN7SL2', 'YES1', 'RRAS', 'ATM', 'MTAP', 'FAS', 'RPL5', 'TP53', 'MAF', 'SLC34A2', 'BCORL1', 'TNFRSF11A', 'MIR4527', 'SPOP', 'PLCG1', 'FOXL2', 'MLLT6', 'RPS15', 'CDH2', 'UBR5', 'NUF2', 'XPO1', 'PDK1', 'DCTN1', 'PML', 'CDK6', 'NT5C2', 'IGF2', 'PCBP1', 'POU2AF1', 'SDHAF2', 'CLTC', 'WWTR1', 'CHN1', 'S100A9', 'MT-TL1', 'PGR', 'AGO1', 'CCNB3', 'UPF1', 'CD274', 'MAP2K4', 'LATS1', 'TCF3', 'ARID5B', 'RELN', 'ACVR1B', 'CUL4A', 'TGFBR2', 'ADARB2', 'ETV6', 'SGK1', 'ZNF384', 'NEGR1', 'QKI', 'ALOX15B', 'FGF8', 'PHLPP1', 'HRAS', 'DDIT3', 'MT-ND4L', 'SFRP4', 'SOS1', 'DAZAP1', 'FLYWCH1', 'FOXP1', 'GOPC', 'RNY3', 'DIS3L2', 'IRF4', 'AKT3', 'NOTCH3', 'MYH9', 'FGF2', 'SCG5', 'PDE4DIP', 'RAD51B', 'SMARCA1', 'MT-CO3', 'RHOH', 'H3P6', 'HIP1', 'SLX4', 'FEV', 'RAD51D', 'APOBEC3B', 'LCK', 'CDKN1B', 'SZT2', 'H4C9', 'ZNRF3', 'SOX10', 'PCLO', 'FLT4', 'LARP4B', 'IFNAR1', 'ELF3', 'GRIN2A', 'H2BC12', 'JAZF1', 'ZNF750', 'HDAC4', 'TYK2', 'DICER1', 'BCL9', 'PIK3CB', 'LCP1', 'MAP4K4', 'PASK', 'H3C4', 'PCM1', 'TPM4', 'ASMTL', 'PAFAH1B2', 'XRCC1', 'POLQ', 'ELL2', 'FGFR3', 'SMARCA2', 'H4C6', 'STAG1', 'DIS3', 'PTPRC', 'KLF6', 'HLF', 'PGBD5', 'CAD', 'LGR5', 'TLX3', 'NSD3', 'SETD6', 'SETD5', 'SHOC2', 'GATA4', 'TAL2', 'INPP4B', 'DNM2', 'KDM6A', 'CDC42', 'MKNK1', 'ARID3B', 'COX6CP18', 'SH2D1A', 'LASP1', 'DDR1', 'SRSF2', 'RNU6-890P', 'MAGED1', 'AFF4', 'KLF2', 'ZBTB20', 'EGFR', 'PRKCI', 'SLFN11', 'XPC', 'MTND2P28', 'SDHD', 'PRSS8', 'ARHGEF28', 'SNX29', 'MEN1', 'SMAD4', 'STK19', 'ETNK1', 'IL6ST', 'RASGEF1A', 'FANCF', 'RNU1-114P', 'WT1', 'SERPINB4', 'MBD4', 'FOLH1', 'BMPR1A', 'STAT6', 'ARID3A', 'ZMYM3', 'RAD54L', 'BLM', 'EWSR1', 'WDCP', 'ZFP36L1', 'IFITM3P7', 'ASPSCR1', 'PRDM16', 'MPEG1', 'BCL11A', 'FSTL1', 'SDC4', 'H2BC4', 'MYCN', 'XBP1', 'HOXB13', 'BTG1', 'H3-3A', 'RNU6-627P', 'TBX3', 'GRM3', 'PAK1', 'SH3GL1', 'RBM15', 'PTPRK', 'PLCG2', 'TRIP11', 'RECQL4', 'ERCC3', 'MAFB', 'SMARCD1', 'RN7SL646P', 'MT-TV', 'LYPLA1P2', 'CEBPA', 'JAK3', 'NAB2', 'ITPKB', 'SPRTN', 'JUN', 'MUTYH', 'IGHD1-14', 'AJUBA', 'TRAF3', 'IL2', 'SETD3', 'MN1', 'IRF2', 'MIR8063', 'MAPKAP1', 'VEGFA', 'NFE2L2', 'MYC', 'H2BC17', 'FAT4', 'CD19', 'KLK2', 'MDM2', 'H1-5', 'MERTK', 'RPS6KB2', 'FAT1', 'LYN', 'MEF2D', 'AMER1', 'SESN1', 'GNAS', 'PPP4R2', 'EPHA5', 'FANCM', 'CIC', 'LIFR', 'BRSK1', 'GTF2I', 'DROSHA', 'MNX1', 'NFATC2', 'MSH2', 'PAX5', 'CXCR4', 'KSR2', 'ARID4A', 'CRTC3', 'AFF3', 'TSHR', 'SS18', 'CTNNB1', 'NQO1', 'ERG', 'RHOA', 'WEE1', 'SDHC', 'NF2', 'PPP2R2A', 'POLE', 'TRAF7', 'KMT5A', 'FES', 'GEN1', 'CDX2', 'TACSTD2', 'PTEN', 'BCR', 'SEPTIN5', 'ERCC1', 'RNU6-39P', 'NUTM2B', 'SSX2', 'RSPO2', 'PMS1', 'SRP72', 'KLF5', 'NUTM2D', 'TCF7L2', 'PIK3CA', 'SEPTIN9', 'SMG1', 'ELN', 'INPP5D', 'HLA-B', 'PDGFRB', 'INPPL1', 'TYMS', 'CLP1', 'PAK5', 'ACKR3', 'MUC1', 'LTK', 'MT-ND4', 'UBA1', 'FANCI', 'DUSP9', 'EP400', 'ONECUT2', 'RET', 'IRF8', 'CBLB', 'FOXO1', 'MIR5685', 'CARD11', 'ZBTB16', 'H3C14', 'TLE2', 'TONSL', 'MYO18A', 'BAP1', 'ELF4', 'YPEL5', 'MAP2K1', 'BABAM1', 'CBL', 'KAT7', 'RUNX1T1', 'GATA6', 'ZNF521', 'GID4', 'IL7R', 'FAF1', 'RNU7-165P', 'FBXW2', 'VAV1', 'CD74', 'PAG1', 'KAT6B', 'HIF1A', 'SAMHD1', 'MTOR', 'POU5F1', 'DOT1L', 'NRG1', 'PREX2', 'APH1A', 'KDM5D', 'LATS2', 'BCL9L', 'KMT2C', 'PRCC', 'ERCC4', 'RAD51'}
1280 genes to keep

In [40]:
import pandas as pd

filtered_columns = filtered_df.columns.tolist()

metadata_df['base_id'] = [f"C{i+1}" for i in range(len(metadata_df))]
metadata_df['full_id'] = metadata_df['base_id'] + '_' + metadata_df['recurStatus']
metadata_df.set_index('full_id', inplace=True)

aligned_metadata = metadata_df.loc[filtered_df.columns]
aligned_metadata['recurStatus'] = aligned_metadata['recurStatus'].replace({'R': 1, 'N': 0}).astype(int)

metadata_fields = ['fu', 'cancerstage_cat', 'er_cat', 'pr_cat', 'her2_cat', 'recurStatus']
metadata_rows = aligned_metadata[metadata_fields].T

combined_with_metadata = pd.concat([filtered_df, metadata_rows])
combined_with_metadata.tail(10)

C:\Users\noapo\AppData\Local\Temp\ipykernel_31304\2954019559.py:10: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  aligned_metadata['recurStatus'] = aligned_metadata['recurStatus'].replace({'R': 1, 'N': 0}).astype(int)

,C1_R,C2_R,C3_R,C4_R,C5_R,C6_R,C7_R,C8_R,C9_R,C10_R,...,C87_N,C88_N,C89_N,C90_N,C91_N,C92_N,C93_N,C94_N,C95_N,C96_N
H2AC16,27.200787,0.000000,0.000000,79.668355,62.826666,0.000000,0.000000,0.0,0.000000,0.000000,...,0.000000,24.934216,0.000000,0.0,245.919199,0.0,73.446859,0.0,0.0,0.0
H3C7,0.000000,0.000000,0.000000,76.179230,30.037567,0.000000,31.739442,0.0,27.407525,0.000000,...,25.992656,23.842206,0.000000,0.0,0.000000,0.0,23.410069,0.0,0.0,0.0
H2AC17,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0
H3C10,0.000000,37.034487,67.444289,33.747953,9.980145,41.241641,10.545603,0.0,9.106300,15.025805,...,0.000000,23.765109,11.124831,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0
fu,2.000000,3.000000,3.000000,4.000000,2.000000,3.000000,10.000000,2.0,3.000000,4.000000,...,2.000000,5.000000,3.000000,5.0,2.000000,3.0,2.000000,3.0,2.0,3.0
cancerstage_cat,3.000000,3.000000,2.000000,2.000000,3.000000,3.000000,3.000000,1.0,1.000000,1.000000,...,2.000000,2.000000,2.000000,2.0,2.000000,2.0,2.000000,2.0,3.0,3.0
er_cat,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.0,1.000000,1.000000,...,0.000000,0.000000,1.000000,1.0,1.000000,1.0,1.000000,1.0,1.0,1.0
pr_cat,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.0,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.0,1.000000,1.0,1.000000,1.0,1.0,1.0
her2_cat,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.0,1.0,1.0
recurStatus,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.0,1.000000,1.000000,...,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0

In [41]:
combined_with_metadata.shape

(1189, 96)

In [42]:
filtered_df.to_csv("C:/Users/noapo/Downloads/filtered_recurrence.tsv", sep="\t")